apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application
    spec:
      initContainers:
        - name: mongo-check
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "until nslookup mongo-0.mongo.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"
      containers:
        - name: application
          image: rinatalimbetov/ralimbetov_application
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthx
              port: 5000
            initialDelaySeconds: 35
            timeoutSeconds: 5
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: MONGO_PORT
            - name: BG_COLOR
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: BG_COLOR
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
